### ISSUE TITLE
For write-csv on numeric data skip the quoting behavior, per field

### ISSUE THREAD

**Issue by benzenwen** [testdouble/clojurescript.csv#20]
## Consumer behavior with quoted numbers
For some consumers of write-csv's output, the quoting and escaping behaviors are needed for strings, but is not desired for numbers.  Such consumers parse the quoted numbers as strings.  Unsurprisingly, perhaps, the particular consumer in question is not configurable (and shall remain nameless to protect the innocent :).

So, the issue is to keep the quoting/escaping behavior of :quote? true but suppress it on a field-by-field basis for numeric data. 

A suggestion is to add a :keep-numbers? true option used in conjunction with :quote? true.  It would skip quoting/escaping when (number? a-field) is true.

(pull request forthcoming for your consideration)

### Current output with :quote? true
```
"100","Description, with, a, bunch, of, commas","0","R","10200"
```

### Desired output with :quote? true :keep-numbers? true
```
100,"Description, with, a, bunch, of, commas",0,"R",10200
```

Thank you for writing this library.

**Comment by rosston** [comment]
Thanks for your patience on this!

I think I'd like to keep this behavior out of clojurescript.csv. Using quotes as a signal for the type of the field seems like a very application-specific problem, and I'd like to avoid owning that additional complexity here. In my experience, every bit of additional complexity in a library is a very small burden on its own, but once you combine it with other small burdens, it makes the library significantly harder to maintain.

As you probably saw when making your PR (thanks for being proactive!), `write-csv` is an extremely simple function that is easy to replicate (`read-csv`, on the other hand, is extremely complex). I'd encourage you to write your own version or use a fork of this library to get your desired CSV writing behavior.
