### ISSUE TITLE
Suggestion: Reference Closure CSV parser in README

### ISSUE THREAD

**Issue by mainej** [testdouble/clojurescript.csv#25]
The Google Closure project includes a [CSV parser](https://google.github.io/closure-library/api/goog.labs.format.csv.html#parse). Like many Closure tools, ironically it is hard to Google for. For those who come to this project needing a CSV parser, but not a writer, you might want to point them to that tool, perhaps by referencing it in the README.

There are still reasons to want to have a CSV parser written in ClojureScript, so I wouldn't remove the parser from this project. But, a link to the Closure tool might help some avoid an extra dependency.

**Comment by rosston** [comment]
Good suggestion! I'll take care of this next week.

**Comment by rosston** [comment]
Added an alternatives section to the README with a link to Google Closure. Thanks for the recommendation!
