### ISSUE TITLE
Fields with quotes do not get auto-quoted

### ISSUE THREAD

**Issue by filipesilva** [testdouble/clojurescript.csv#30]
I found another difference in behaviour between this library and clj's `clojure.data.csv`:

```clojure
(ns user
  (:require 
   #?@(:clj  [[clojure.data.csv :as csv]]
       :cljs [[testdouble.cljs.csv :as csv]]))
  #?(:clj (:import [java.io StringWriter])))

(defn csv-str [data]
  #?(:clj (let [writer (StringWriter.)]
            (csv/write-csv writer data)
            (str writer))
     :cljs (csv/write-csv data)))

(csv-str [["a\"b\""]])
;; in clj "\"a\"\"b\"\"\""
;; in cljs "a\"b\""
```

`clojure.data.csv` auto-quotes when there's a quote inside. It also adds another set of quotes around the inside quotes, I don't quite understand why.

**Comment by rosston** [comment]
>It also adds another set of quotes around the inside quotes, I don't quite understand why.

Because that's how RFC4180 says to escape quotes! It's quite annoying to code around IMO (check out `read-csv` 😅). From [section 2.7](https://www.rfc-editor.org/rfc/rfc4180#section-2):
>If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote.  For example:
>
>       "aaa","b""bb","ccc"

**Comment by rosston** [comment]
Fixed/released in 0.8.0! 🎉 Thanks for making `write-csv` fully RFC 4180 compliant!

**Comment by filipesilva** [comment]
Heh I had no idea that was why, I just happened to have a [clj codebase](https://github.com/filipesilva/roam-to-csv) that handled a lot of weird csv input with `clojure.data.csv` and needed to port it to js too :D

**Comment by rosston** [comment]
>handled a lot of weird csv input

I'm sorry for your loss. 😏 😆
