### ISSUE TITLE
Outdated clojars version

### ISSUE THREAD

**Issue by Frozenlock** [testdouble/clojurescript.csv#4]
Looks like the code has been updated for version 0.3.0, but neither the project.clj nor the clojars version reflect this.

It also appears that version 0.3.0 will fix #2.

**Comment by kbaribeau** [comment]
Hey @bostonaholic I have this ready to go, but I don't have permissions on Clojars for the testdouble group. Can you add me?

https://clojars.org/groups/testdouble

**Comment by bostonaholic** [comment]
Hah. So you have access to the repo and I have access to clojars. Added you as an admin @kbaribeau. Let me know if doesn't work out.

**Comment by kbaribeau** [comment]
Alright, I've pushed 0.3.0 to Clojars.

I checked it on an old project of mine, but I'd also appreciate anyone who can chime in with confirmation that it's working for them.

**Comment by kbaribeau** [comment]
Fixed.
