### ISSUE TITLE
read-csv splits on separators within quoted fields, maintains quotes

### ISSUE THREAD

**Issue by justindbelanger** [testdouble/clojurescript.csv#8]
I would expect that the read-csv function would skip separator characters--like commas--when they're inside of quoted fields. Also, I'd expect the read-csv function to remove such quotes around each field. I.e., evaluating ```(read-csv "Who,Where\n\"Me, myself, and I\",\"The middle of nowhere\"")``` produces the following.
Actual: 
```(["Who" "Where"] ["\"Me" " myself" " and I\"" "\"The middle of nowhere\""])```
Expected: 
```(["Who" "Where"] ["Me, myself, and I" "The middle of nowhere"])```

**Comment by rosston** [comment]
Good catch, thanks for raising it! I have an idea on how to approach this, but I won't be able to get to it until next week.

**Comment by rosston** [comment]
Yeah, of course! You are welcome to take a crack at it. If you do, I'd say the only preferences are that there are tests based on [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt), and of course that they pass by the time a PR is opened. 🙂 

Sorry for the lack of updates. I've been working on it, albeit slowly. I've added failing tests (which was pretty straightfoward) based on RFC 4180 and also found that `write-csv` is incorrect for double quotes inside a quoted field.

Fixing the problem looks a bit more complex than I originally envisioned. The current code for `read-csv` simply does a series of string splits, which is a really simple approach. But to support RFC 4180, I think the only way forward is to loop through the string one character at a time and keep track of a bunch of state (e.g., are we in a quoted field? are we at the end of a field?) to build up the parsed rows. I've got that code more or less done for unquoted fields. Next I'll be trying to make it work for quoted fields.

**Comment by rosston** [comment]
I have a very much in-progress branch with a (I think) a working `read-csv` implementation that respects quotes and special characters in quoted fields. It's not pretty, and I'm sure there's a lot of cleanup that can happen, but it is functioning. Here's the diff: https://github.com/testdouble/clojurescript.csv/compare/fix-read-quoted-fields

I'll open a PR for it soon. I plan to keep working to clean up the `read-csv` implementation and also fix the new failing `write-csv` test.

**Comment by justindbelanger** [comment]
I just read over your work on the new branch--nice! Yeah, it seems like the ```read-csv``` function might need some more TLC. 😅 Overall it looks really good, though!

**Comment by rosston** [comment]
The work in #9 has been deployed in v0.4.0. All the unit tests pass, but we're not actively using this project in production, so please let us know if you run into any issues. 🙂
